version: "3.9"

services:
  cockroachdb:
    image: cockroachdb/cockroach:v23.2.5
    command: start-single-node --insecure --store=attrs=ssd,path=/var/lib/cockroach/
    restart: unless-stopped
    volumes:
      - cockroach-data:/var/lib/cockroach/
    ports:
      - "26257:26257"
      - "8080:8080"

  nakama:
    image: heroiclabs/nakama:3.20.0
    restart: unless-stopped
    depends_on:
      - cockroachdb
    entrypoint:
      - "/bin/sh"
      - "-ecx"
    command:
      - >
        /nakama/nakama migrate up --database.address root@cockroachdb:26257 &&
        exec /nakama/nakama --config /nakama/data/local.yml --database.address root@cockroachdb:26257
    volumes:
      - ./local.yml:/nakama/data/local.yml
      - ./modules:/nakama/data/modules
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"

volumes:
  cockroach-data:
